version: "3.8"

services:
  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@database:5432/mydatabase?sslmode=disable
      - JWT_SECRET=paN7$zXk!vR9Lm3bQ5W2tXy8dT@rCk1H
    depends_on:
      - database
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx/conf.d:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot

  certbot:
    image: certbot/certbot
    depends_on:
      - frontend
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot -w /var/www/certbot
      --email dokebi871218@gmail.com
      -d myportfolioapp.com --agree-tos --non-interactive"

volumes:
  postgres_data:
  certbot-etc:
  certbot-var:
