// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FoodLog struct {
	ID       int      `json:"id"`
	Name     string   `json:"name"`
	Calories *float64 `json:"calories,omitempty"`
	Protein  *float64 `json:"protein,omitempty"`
	Fat      *float64 `json:"fat,omitempty"`
	Carbs    *float64 `json:"carbs,omitempty"`
	Quantity *string  `json:"quantity,omitempty"`
	LoggedAt *string  `json:"logged_at,omitempty"`
}

type FoodLogInput struct {
	Name     string   `json:"name"`
	Calories *float64 `json:"calories,omitempty"`
	Protein  *float64 `json:"protein,omitempty"`
	Fat      *float64 `json:"fat,omitempty"`
	Carbs    *float64 `json:"carbs,omitempty"`
	Quantity *string  `json:"quantity,omitempty"`
	LoggedAt *string  `json:"logged_at,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
