package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"
	"fmt"
	"time"

	"github.com/DodoroGit/My_Portfolio/backend/database"
	"github.com/DodoroGit/My_Portfolio/backend/graph/generated"
	"github.com/DodoroGit/My_Portfolio/backend/graph/model"
)

// 新增食物紀錄
func (r *mutationResolver) AddFoodLog(ctx context.Context, input model.FoodLogInput) (*model.FoodLog, error) {
	userID, ok := ctx.Value("user_id").(int)
	if !ok {
		return nil, fmt.Errorf("找不到登入使用者資訊")
	}

	if input.LoggedAt == nil {
		return nil, fmt.Errorf("請提供 loggedAt 日期")
	}

	t, err := time.Parse("2006-01-02", *input.LoggedAt)
	if err != nil {
		return nil, fmt.Errorf("日期格式錯誤：%v", err)
	}

	var insertedID int
	err = database.DB.QueryRow(`
		INSERT INTO food_logs (user_id, name, calories, protein, fat, carbs, quantity, logged_at)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
		RETURNING id`,
		userID, input.Name, input.Calories, input.Protein, input.Fat, input.Carbs, input.Quantity, t,
	).Scan(&insertedID)

	if err != nil {
		return nil, err
	}

	return &model.FoodLog{
		ID:       insertedID,
		Name:     input.Name,
		Calories: input.Calories,
		Protein:  input.Protein,
		Fat:      input.Fat,
		Carbs:    input.Carbs,
		Quantity: input.Quantity,
		LoggedAt: input.LoggedAt,
	}, nil
}

// 查詢食物紀錄
func (r *queryResolver) MyFoodLogs(ctx context.Context) ([]*model.FoodLog, error) {
	userID, ok := ctx.Value("user_id").(int)
	if !ok {
		return nil, fmt.Errorf("找不到登入使用者資訊")
	}

	rows, err := database.DB.Query(`
		SELECT id, name, calories, protein, fat, carbs, quantity, logged_at
		FROM food_logs WHERE user_id = $1`, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var logs []*model.FoodLog
	for rows.Next() {
		var f model.FoodLog
		var t time.Time
		if err := rows.Scan(&f.ID, &f.Name, &f.Calories, &f.Protein, &f.Fat, &f.Carbs, &f.Quantity, &t); err != nil {
			continue
		}
		formatted := t.Format("2006-01-02")
		f.LoggedAt = &formatted
		logs = append(logs, &f)
	}
	return logs, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
